// 全项目统一图标库：Phosphor（@phosphor-icons/react）。
// 这里把项目里用到的名字映射到 Phosphor 等价图标，业务/组件代码继续用原名（JSX 不用改）。
// Phosphor 一个图标支持多种 weight：默认 regular=线性；需要面型用 weight="fill"。
// 详见 docs/TOKENS.md 图标小节、docs/DECISIONS.md DEC-007。
export {
  WarningCircle as AlertCircleIcon,
  Warning as AlertTriangleIcon,
  ArrowLeft as ArrowLeftIcon,
  ArrowRight as ArrowRightIcon,
  ArrowUpRight as ArrowUpRightIcon,
  SealCheck as BadgeCheckIcon,
  Bell as BellIcon,
  TextB as BoldIcon,
  BookOpen as BookOpenIcon,
  Cube as BoxIcon,
  CheckCircle as CheckCircleIcon,
  Check as CheckIcon,
  Info as InfoIcon,
  XCircle as XCircleIcon,
  CaretDown as ChevronDownIcon,
  CaretLeft as ChevronLeftIcon,
  CaretRight as ChevronRightIcon,
  CaretUp as ChevronUpIcon,
  CaretUpDown as ChevronsUpDownIcon,
  Circle as CircleIcon,
  Copy as CopyIcon,
  CreditCard as CreditCardIcon,
  Database as DatabaseIcon,
  FileCode as FileCodeIcon,
  FileText as FileTextIcon,
  Folder as FolderIcon,
  House as HomeIcon,
  TextItalic as ItalicIcon,
  SquaresFour as LayoutGridIcon,
  Lightbulb as LightbulbIcon,
  Link as LinkIcon,
  SignOut as LogOutIcon,
  ChatCircleDots as MessageSquareWarningIcon,
  DotsThree as MoreHorizontalIcon,
  NavigationArrow as NavigationIcon,
  Package as PackageIcon,
  Sidebar as PanelLeftIcon,
  Plus as PlusIcon,
  MagnifyingGlass as SearchIcon,
  Gear as SettingsIcon,
  Sparkle as SparklesIcon,
  Star as StarIcon,
  Star as StarOffIcon,
  Terminal as TerminalIcon,
  TextUnderline as UnderlineIcon,
  User as UserIcon,
  Trash as Trash2Icon,
  Code as Code2Icon,
  X as XIcon,
  CircleNotch as Loader2Icon,
} from "@phosphor-icons/react"
