// 全项目统一图标库：Tabler Icons（@tabler/icons-react）。
// 选它的原因：线性图标的线宽可调（strokeWidth），且有成套的实心(*Filled)变体——
// 兼顾"粗细可控"与"面型/实心"。线性默认线宽由全局 CSS（.tabler-icon { stroke-width }）统一控制，
// 面型用对应的 *Filled 组件。详见 docs/TOKENS.md 图标小节、docs/DECISIONS.md DEC-009。
// 这里把项目里用到的名字映射到 Tabler 等价图标，业务/组件 JSX 不用改。
export {
  IconAlertCircle as AlertCircleIcon,
  IconAlertTriangle as AlertTriangleIcon,
  IconArrowLeft as ArrowLeftIcon,
  IconArrowRight as ArrowRightIcon,
  IconArrowUpRight as ArrowUpRightIcon,
  IconRosetteDiscountCheck as BadgeCheckIcon,
  IconBell as BellIcon,
  IconBold as BoldIcon,
  IconBuilding as BuildingIcon,
  IconBriefcase as BriefcaseIcon,
  IconCalendar as CalendarIcon,
  IconChecklist as ChecklistIcon,
  IconHeadset as HeadsetIcon,
  IconMessageCircle as MessageCircleIcon,
  IconSchool as SchoolIcon,
  IconChartLine as ChartLineIcon,
  IconMapPin as MapPinIcon,
  IconReportMoney as ReportMoneyIcon,
  IconTarget as TargetIcon,
  IconSitemap as SitemapIcon,
  IconBook as BookOpenIcon,
  IconBox as BoxIcon,
  IconCircleCheck as CheckCircleIcon,
  IconCheck as CheckIcon,
  IconChevronDown as ChevronDownIcon,
  IconChevronLeft as ChevronLeftIcon,
  IconChevronRight as ChevronRightIcon,
  IconChevronUp as ChevronUpIcon,
  IconChevronsLeft as ChevronsLeftIcon,
  IconChevronsRight as ChevronsRightIcon,
  IconLock as LockIcon,
  IconLockOpen as LockOpenIcon,
  IconSelector as ChevronsUpDownIcon,
  IconCircle as CircleIcon,
  IconCode as Code2Icon,
  IconCopy as CopyIcon,
  IconCreditCard as CreditCardIcon,
  IconDatabase as DatabaseIcon,
  IconFileCode as FileCodeIcon,
  IconFileText as FileTextIcon,
  IconFolder as FolderIcon,
  IconFolderFilled as FolderFilledIcon,
  IconHome as HomeIcon,
  IconInfoCircle as InfoIcon,
  IconItalic as ItalicIcon,
  IconLayoutGrid as LayoutGridIcon,
  IconBulb as LightbulbIcon,
  IconLink as LinkIcon,
  IconLoader2 as Loader2Icon,
  IconLogout as LogOutIcon,
  IconMessageReport as MessageSquareWarningIcon,
  IconDots as MoreHorizontalIcon,
  IconNavigation as NavigationIcon,
  IconPackage as PackageIcon,
  IconLayoutSidebar as PanelLeftIcon,
  IconPlus as PlusIcon,
  IconZoom as SearchIcon,
  IconSettings as SettingsIcon,
  IconSparkles as SparklesIcon,
  IconStar as StarIcon,
  IconStarOff as StarOffIcon,
  IconTerminal2 as TerminalIcon,
  IconTrash as Trash2Icon,
  IconUnderline as UnderlineIcon,
  IconUser as UserIcon,
  IconCircleX as XCircleIcon,
  IconX as XIcon,
  // 面型/实心（示例与选中态用）
  IconStarFilled as StarFilledIcon,
  IconCircleCheckFilled as CheckCircleFilledIcon,
  IconHomeFilled as HomeFilledIcon,
  IconBellFilled as BellFilledIcon,
  IconUserFilled as UserFilledIcon,
  IconDatabaseFilled as DatabaseFilledIcon,
} from "@tabler/icons-react"

// 自定义/上传图标：统一从这里出口（与内置 Tabler 图标同一入口）。
// 接入第三方图标库同理——在上面 import 段加 `IconX as XIcon` 即可，调用方无需感知来源。
export { ContractIcon, ContractFilledIcon } from "@/lib/icons-custom"
