import { test, expect } from "@playwright/test"

// 视觉回归：渲染关键界面 → 与基线截图 diff。像素漂移超阈值即 fail 并出对比图。
// 截组件局部（定位器）比整页更稳；头像图片用 mask 屏蔽（异步加载、非视觉契约）。

test.beforeEach(async ({ page }) => {
  // 关 CSS 过渡/动画，避免截图抓到中间帧
  await page.addInitScript(() => {
    const style = document.createElement("style")
    style.textContent = "*,*::before,*::after{transition:none!important;animation:none!important}"
    document.documentElement.appendChild(style)
  })
})

test("顶栏 TopBar", async ({ page }) => {
  await page.goto("/#top-bar")
  const bar = page.locator('[data-slot="top-bar"]').first()
  await expect(bar).toBeVisible()
  await expect(bar).toHaveScreenshot("top-bar.png", {
    mask: [page.locator('[data-slot="avatar"]')],
  })
})

test("网站卡片容器", async ({ page }) => {
  await page.goto("/#website-standards")
  const card = page.locator('[data-website-card-container]').filter({ hasText: "内部区域" })
  await expect(card).toHaveCount(1)
  await expect(card).toBeVisible()
  await expect(card).toHaveScreenshot("website-card-container.png")
})

test("网站卡片容器跟随全局阴影", async ({ page }) => {
  await page.addInitScript(() => {
    window.localStorage.setItem("fx-ui-theme-config", JSON.stringify({ shadowLevel: "none" }))
  })
  await page.goto("/#website-standards")
  const card = page.locator('[data-website-card-container]').filter({ hasText: "内部区域" })
  await expect(card).toHaveCount(1)
  await expect(card).toHaveCSS("box-shadow", "none")
})

test("客户列表页模板", async ({ page }) => {
  await page.goto("/#template-customer-list")
  const frame = page.locator("#template-customer-list").locator("xpath=following-sibling::*[1]")
  await expect(frame).toBeVisible()
  await expect(frame).toHaveScreenshot("customer-list-template.png", {
    mask: [page.locator('[data-slot="avatar"]')],
  })
})

test("Button 交互调试台", async ({ page }) => {
  await page.goto("/#button")
  const pg = page.locator("#playground")
  await expect(pg).toBeVisible()
  await expect(pg).toHaveScreenshot("button-playground.png")
})

test("Tag 交互调试台", async ({ page }) => {
  await page.goto("/#tag")
  const pg = page.locator("#tag-playground")
  await expect(pg).toBeVisible()
  await expect(pg).toHaveScreenshot("tag-playground.png")
})

test("Input 组件制作台", async ({ page }) => {
  await page.goto("/#input")
  const workbench = page.locator("#input-playground")
  await expect(workbench).toBeVisible()
  await expect(workbench.getByRole("treeitem")).toHaveCount(0)
  await expect(workbench.locator("label")).toHaveText(["占位文字", "输入类型", "前置内容", "后置内容", "尺寸", "禁用", "报错"])
  await expect(workbench.getByText("交互状态", { exact: true })).toHaveCount(0)
  await expect(workbench).toContainText("录入普通文本。")
  const leadingControl = workbench.locator("label").filter({ hasText: "前置内容" }).locator("..")
  const trailingControl = workbench.locator("label").filter({ hasText: "后置内容" }).locator("..")
  await leadingControl.getByRole("button", { name: "符号", exact: true }).click()
  await trailingControl.getByRole("button", { name: "符号", exact: true }).click()
  await expect(workbench.locator('[data-slot="input-group"]')).toHaveCount(1)
  await expect(workbench.locator('[data-slot="input-affix"]')).toHaveCount(2)
  await expect(workbench.locator('[data-slot="input-workbench-preview"]')).toContainText("%")
  await leadingControl.getByRole("button", { name: "无", exact: true }).click()
  await trailingControl.getByRole("button", { name: "无", exact: true }).click()
  await leadingControl.getByRole("button", { name: "标签", exact: true }).click()
  const inputGroup = workbench.locator('[data-slot="input-workbench-preview"] [data-slot="input-group"]')
  const inputAddon = workbench.locator('[data-slot="input-workbench-preview"] [data-slot="input-addon"]')
  await expect(inputAddon).toHaveCount(1)
  const groupBackground = await inputGroup.evaluate((element) => getComputedStyle(element).backgroundColor)
  const addonBackground = await inputAddon.evaluate((element) => getComputedStyle(element).backgroundColor)
  const groupBorder = await inputGroup.evaluate((element) => getComputedStyle(element).borderColor)
  const addonDivider = await inputAddon.evaluate((element) => getComputedStyle(element).borderRightColor)
  expect(addonBackground).toBe(groupBackground)
  expect(addonDivider).toBe(groupBorder)
  await leadingControl.getByRole("button", { name: "无", exact: true }).click()
  await workbench.locator("label").filter({ hasText: "输入类型" }).locator("..").getByRole("button", { name: "搜索", exact: true }).click()
  const searchInput = workbench.locator('[data-slot="input-workbench-preview"] [data-slot="input"]')
  await expect(searchInput).toHaveAttribute("type", "search")
  await expect(leadingControl.getByRole("button", { name: "搜索图标", exact: true })).toBeVisible()
  await expect(workbench.locator('[data-slot="input-workbench-preview"] [data-slot="input-affix"]')).toHaveCount(1)
  await expect(leadingControl.getByRole("button", { name: "邮箱图标", exact: true })).toHaveCount(0)
  await expect(trailingControl.getByRole("button", { name: "显示密码", exact: true })).toHaveCount(0)
  await trailingControl.getByRole("button", { name: "搜索图标", exact: true }).click()
  const searchAffix = workbench.locator('[data-slot="input-workbench-preview"] [data-slot="input-affix"]')
  await expect(searchAffix).toHaveCount(1)
  await expect(searchAffix).toHaveAttribute("data-side", "end")
  await workbench.locator("label").filter({ hasText: "输入类型" }).locator("..").getByRole("button", { name: "文本", exact: true }).click()
  await workbench.locator("label").filter({ hasText: "输入类型" }).locator("..").getByRole("button", { name: "搜索", exact: true }).click()
  await expect(searchAffix).toHaveAttribute("data-side", "start")
  await expect(workbench.locator('[data-slot="input-workbench-preview"] [data-slot="input-action"]')).toHaveCount(0)
  await searchInput.fill("客户")
  const clearSearch = workbench.locator('[data-slot="input-workbench-preview"] [data-slot="input-action"]')
  await expect(clearSearch).toHaveAttribute("aria-label", "清除搜索")
  await clearSearch.click()
  await expect(searchInput).toHaveValue("")
  await expect(clearSearch).toHaveCount(0)
  await expect(trailingControl.getByRole("button", { name: "清除", exact: true })).toHaveCount(0)
  await trailingControl.getByRole("button", { name: "无", exact: true }).click()
  await workbench.locator("label").filter({ hasText: "输入类型" }).locator("..").getByRole("button", { name: "文本", exact: true }).click()
  const workbenchCard = workbench.locator(':scope > [data-slot="card"]')
  await workbenchCard.evaluate((element) => {
    element.scrollIntoView()
    window.scrollBy(0, -72)
  })
  await expect(workbenchCard).toHaveScreenshot("input-playground-default.png")
  await workbench.locator("label").filter({ hasText: "输入类型" }).locator("..").getByRole("button", { name: "数字", exact: true }).click()
  const numberInput = workbench.locator('[data-slot="input-workbench-preview"] [data-slot="input"]')
  await expect(numberInput).toHaveAttribute("type", "number")
  await expect(numberInput).toHaveScreenshot("input-number.png")
  await workbench.locator("label").filter({ hasText: "输入类型" }).locator("..").getByRole("button", { name: "搜索", exact: true }).click()
  await trailingControl.getByRole("button", { name: "主搜索", exact: true }).click()
  const primaryAction = workbench.locator('[data-slot="input-workbench-preview"] [data-slot="input-action"]')
  await expect(primaryAction).toHaveAttribute("data-variant", "primary")
  await expect(primaryAction).toHaveText("搜索")
  await expect(workbench.locator('[data-slot="input-workbench-preview"]')).toHaveScreenshot("input-primary-action.png")
  await trailingControl.getByRole("button", { name: "无", exact: true }).click()
  await workbench.locator("label").filter({ hasText: "输入类型" }).locator("..").getByRole("button", { name: "邮箱", exact: true }).click()
  await expect(leadingControl.getByRole("button", { name: "搜索图标", exact: true })).toHaveCount(0)
  await expect(trailingControl.getByRole("button", { name: "清除", exact: true })).toHaveCount(0)
  await expect(leadingControl.getByRole("button", { name: "邮箱图标", exact: true })).toBeVisible()
  await expect(workbench.locator('[data-slot="input-workbench-preview"] [data-slot="input-group"]')).toHaveCount(1)
  await expect(workbench.locator('[data-slot="input-workbench-preview"] [data-slot="input-affix"]')).toHaveCount(1)
  const emailInput = workbench.locator('[data-slot="input-workbench-preview"] [data-slot="input"]')
  await emailInput.fill("invalid-email")
  expect(await emailInput.evaluate((element) => (element as HTMLInputElement).validity.typeMismatch)).toBe(true)
  await emailInput.press("Tab")
  await expect(emailInput).toHaveAttribute("aria-invalid", "true")
  await expect(workbench.getByText("请输入有效的邮箱地址。", { exact: true })).toHaveCount(0)
  await emailInput.fill("name@example.com")
  await expect(emailInput).not.toHaveAttribute("aria-invalid", "true")
  await expect(workbench.getByText("请输入有效的邮箱地址。", { exact: true })).toHaveCount(0)
  await expect(workbench.getByRole("button", { name: "校验格式", exact: true })).toHaveCount(0)
  await workbench.getByRole("button", { name: "编辑组件", exact: true }).click()
  const fieldControl = workbench.locator("label").filter({ hasText: "字段包装" }).locator("..")
  await fieldControl.getByRole("button", { name: "字段", exact: true }).click()
  const wrappedEmailInput = workbench.locator('[data-slot="input-workbench-preview"] [data-slot="input"]')
  await wrappedEmailInput.fill("invalid-email")
  await wrappedEmailInput.press("Tab")
  await expect(wrappedEmailInput).toHaveAttribute("aria-invalid", "true")
  await expect(workbench.getByText("字段名称", { exact: true })).toBeVisible()
  await expect(workbench.getByText("请输入有效的邮箱地址。", { exact: true })).toBeVisible()
  await workbench.getByRole("button", { name: "完成编辑", exact: true }).click()
  await workbench.locator("label").filter({ hasText: "输入类型" }).locator("..").getByRole("button", { name: "密码", exact: true }).click()
  const passwordInput = workbench.locator('[data-slot="input-workbench-preview"] [data-slot="input"]')
  await expect(passwordInput).toHaveAttribute("type", "password")
  const passwordToggle = workbench.locator('[data-slot="input-workbench-preview"] [data-slot="input-action"]')
  await expect(passwordToggle).toHaveAttribute("aria-label", "显示密码")
  await passwordToggle.click()
  await expect(passwordInput).toHaveAttribute("type", "text")
  await expect(passwordToggle).toHaveAttribute("aria-label", "隐藏密码")
  await workbench.locator("label").filter({ hasText: "输入类型" }).locator("..").getByRole("button", { name: "文本", exact: true }).click()
  await workbench.locator("label").filter({ hasText: "禁用" }).locator("..").getByRole("button", { name: "是", exact: true }).click()
  await expect(workbench.locator('[data-slot="input-workbench-preview"] [data-slot="input"]')).toBeDisabled()
  await workbench.locator("label").filter({ hasText: "禁用" }).locator("..").getByRole("button", { name: "否", exact: true }).click()
  await workbench.locator("label").filter({ hasText: "报错" }).locator("..").getByRole("button", { name: "是", exact: true }).click()
  await expect(workbench.locator('[data-slot="input-workbench-preview"] [data-slot="input"]')).toHaveAttribute("aria-invalid", "true")
  await workbench.locator("label").filter({ hasText: "报错" }).locator("..").getByRole("button", { name: "否", exact: true }).click()
  await workbench.locator("label").filter({ hasText: "输入类型" }).locator("..").getByRole("button", { name: "文本", exact: true }).click()
  await workbench.getByRole("button", { name: "编辑组件", exact: true }).click()
  await expect(workbench.getByRole("treeitem")).toHaveCount(4)

  const editingLeadingControl = workbench.locator("label").filter({ hasText: "前置内容" }).locator("..")
  await editingLeadingControl.getByRole("button", { name: "标签", exact: true }).click()
  await expect(workbench.locator('[data-slot="input-group"]')).toBeVisible()
  await expect(workbench.locator('[data-slot="input-addon"]')).toHaveCount(1)

  await workbench.getByRole("treeitem", { name: /输入框/ }).click()
  const placeholderControl = workbench.locator("label").filter({ hasText: "占位文字" }).locator("..")
  await placeholderControl.getByRole("textbox").fill("搜索客户")
  await expect(workbench.getByPlaceholder("搜索客户", { exact: true })).toBeVisible()

  await workbench.getByRole("treeitem", { name: /语义 Token/ }).click()
  const preview = workbench.locator('[data-slot="input-workbench-preview"]')
  const defaultBackground = await preview.locator('[data-slot="input-group"]').evaluate((element) => getComputedStyle(element).backgroundColor)
  await workbench.getByRole("button", { name: "弱化表面", exact: true }).click()
  await expect(preview).toHaveAttribute("data-surface-token", "muted")
  const mutedBackground = await preview.locator('[data-slot="input-group"]').evaluate((element) => getComputedStyle(element).backgroundColor)
  expect(mutedBackground).not.toBe(defaultBackground)

  await workbench.getByRole("button", { name: "代码", exact: true }).click()
  await expect(workbench.locator("code")).toContainText('"--surface": "var(--muted)"')
  await workbench.getByRole("button", { name: "预览", exact: true }).click()

  await workbench.getByRole("treeitem", { name: /状态语义/ }).click()
  const stateAssignments = workbench.locator('[data-slot="component-playground-state-assignments"]')
  await expect(stateAssignments.getByRole("button")).toHaveCount(6)
  await expect(stateAssignments).toContainText("input")
  await expect(stateAssignments).toContainText("primary")
  await expect(stateAssignments).toContainText("destructive")
  await expect(stateAssignments).toContainText("neutrals-07")
  await expect(stateAssignments).toContainText("brand-09")
  await expect(stateAssignments).toContainText("neutrals-03")
  await expect(stateAssignments).toContainText("red-09")
  await expect(stateAssignments).not.toContainText("oklch(")
  await expect(stateAssignments).not.toContainText("rgb(")
  const normalAssignment = stateAssignments.getByRole("button", { name: /正常.*边框.*input/ })
  const normalTokenColor = await normalAssignment.locator('[aria-hidden="true"]').evaluate((element) => getComputedStyle(element).backgroundColor)
  const normalBorder = await preview.locator('[data-slot="input-group"]').evaluate((element) => getComputedStyle(element).borderColor)
  expect(normalBorder).toBe(normalTokenColor)
  const invalidAssignment = stateAssignments.getByRole("button", { name: /错误.*边框.*destructive/ })
  const invalidTokenColor = await invalidAssignment.locator('[aria-hidden="true"]').evaluate((element) => getComputedStyle(element).backgroundColor)
  await invalidAssignment.click()
  await expect(preview.locator('[data-slot="input"]')).toHaveAttribute("aria-invalid", "true")
  await expect(preview.locator('[data-slot="input-group"]')).toHaveCSS("border-color", invalidTokenColor)
  await expect(workbench.locator('[data-slot="component-playground-validation"]')).toContainText(`border: ${invalidTokenColor}`)
  const invalidBorder = await preview.locator('[data-slot="input-group"]').evaluate((element) => getComputedStyle(element).borderColor)
  expect(invalidBorder).not.toBe(normalBorder)
  expect(invalidBorder).toBe(invalidTokenColor)
  await workbenchCard.evaluate((element) => {
    element.scrollIntoView()
    window.scrollBy(0, -72)
  })
  await expect(workbenchCard).toHaveScreenshot("input-workbench.png")

  await workbench.getByRole("button", { name: "完成编辑", exact: true }).click()
  await expect(workbench.getByRole("treeitem")).toHaveCount(0)
  await expect(preview).toHaveAttribute("data-surface-token", "surface")
  await expect(preview.locator('[data-slot="input-group"]')).toHaveCount(0)
  await expect(preview.locator('[data-slot="input-affix"]')).toHaveCount(0)
  await expect(preview.locator('[data-slot="input-addon"]')).toHaveCount(0)
  await expect(workbench.getByPlaceholder("请输入", { exact: true })).toBeVisible()
  await expect(preview.locator('[data-slot="input"]')).not.toHaveAttribute("aria-invalid", "true")
  await expect(workbench.locator("label")).toHaveText(["占位文字", "输入类型", "前置内容", "后置内容", "尺寸", "禁用", "报错"])
})

test("DatePicker 日期选择器", async ({ page }) => {
  await page.goto("/#date-picker")
  const picker = page.locator('[data-slot="date-picker"]').first()
  await expect(picker).toBeVisible()
  await expect(picker).toContainText("2026/07/15")
  const trigger = picker.locator('[data-slot="date-picker-trigger"]')
  await trigger.click()
  await expect(page.locator('[data-slot="calendar"]')).toBeVisible()
  await expect(picker).toHaveScreenshot("date-picker.png")
})
