import type { ReactNode } from "react";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { FileRelationMap, type FileRelation } from "@/pages/docs/governance/governance-graph-primitives";

function LayerCard({ title, desc, emphasis = false }: { title: string; desc: string; emphasis?: boolean }) {
  return <div className={`rounded-xl border px-4 py-3 ${emphasis ? "border-primary bg-primary/10" : "border-border bg-muted"}`}><div className="text-sm font-semibold text-foreground">{title}</div><div className="mt-1 text-xs leading-5 text-muted-foreground">{desc}</div></div>;
}

function LayerRow({ label, note, children }: { label: string; note?: string; children: ReactNode }) {
  return <div className="grid gap-3 rounded-2xl border border-border bg-background/70 p-4 md:grid-cols-[120px_minmax(0,1fr)]"><div><div className="text-sm font-medium text-muted-foreground">{label}</div>{note ? <div className="mt-2 text-xs leading-5 text-muted-foreground">{note}</div> : null}</div><div className="grid gap-3 md:grid-cols-2 xl:grid-cols-4">{children}</div></div>;
}

export function FxUiSystemDiagram({ scope, systemRelations }: { scope: "site" | "project"; systemRelations: { site: FileRelation[]; project: FileRelation[] } }) {
  if (scope === "project") {
    return <Tabs defaultValue="category" className="flex flex-col gap-4"><TabsList className="w-fit"><TabsTrigger value="category">分类视图</TabsTrigger><TabsTrigger value="relations">文件关系</TabsTrigger></TabsList><TabsContent value="category" className="mt-0"><div className="flex flex-col gap-3 rounded-xl border border-border bg-card p-4"><LayerRow label="最终产物" note="项目能力最终不是 dist，而是能支撑真实业务页面。"><LayerCard title="真实业务项目页面" desc="后台列表、详情、编辑、设置、报表等完整页面" emphasis /></LayerRow><LayerRow label="页面" note="把常见业务结构沉淀为可复用页面。"><LayerCard title="页面 Blocks / layouts" desc="常见页面骨架和组合方式" /><LayerCard title="src/components/fx" desc="公司组合组件，承接高频业务结构" /><LayerCard title="docs/LAYOUTS.md" desc="业务后台页面布局规范" /></LayerRow><LayerRow label="基础能力" note="组件、token、规则数据共同支撑页面。"><LayerCard title="src/components/ui" desc="shadcn open-code 基础组件" /><LayerCard title="theme/fx-theme.css" desc="公司视觉 token 真相源" /><LayerCard title="docs + docs/data" desc="给人和 AI 共同消费的规范与事实" /></LayerRow><LayerRow label="工程工具" note="这些不是页面本身，但决定项目怎么被检查、分发和复用。"><LayerCard title="scripts/check-*" desc="契约、token、文档站、组件 manifest 检查" /><LayerCard title=".ai/rules + .agents/skills" desc="AI 工作规则和项目 skill" /><LayerCard title="registry/fx-theme.json" desc="主题分发包" /><LayerCard title="package.json" desc="依赖、脚本和检查命令" /></LayerRow><LayerRow label="底座" note="本地开发和构建运行的基础。"><LayerCard title="shadcn/ui" desc="基础组件来源" /><LayerCard title="Vite / React / Tailwind" desc="开发、渲染和样式技术栈" /><LayerCard title="dist/" desc="构建产物，不手改" /></LayerRow></div></TabsContent><TabsContent value="relations" className="mt-0"><FileRelationMap relations={systemRelations.project} /></TabsContent></Tabs>;
  }

  return <Tabs defaultValue="category" className="flex flex-col gap-4"><TabsList className="w-fit"><TabsTrigger value="category">分类视图</TabsTrigger><TabsTrigger value="relations">文件关系</TabsTrigger></TabsList><TabsContent value="category" className="mt-0"><div className="flex flex-col gap-3 rounded-xl border border-border bg-card p-4"><LayerRow label="最终产物"><LayerCard title="fx-ui 文档站页面" desc="开发者查看组件、token、规范和现状的完整网站" emphasis /></LayerRow><LayerRow label="运行层"><LayerCard title="src/main.tsx" desc="React 应用入口" /><LayerCard title="src/App.tsx" desc="页面路由、导航、示例和现状页渲染" /><LayerCard title="npm run check" desc="交付前质量门禁" /></LayerRow><LayerRow label="内容层"><LayerCard title="组件体系" desc="src/components/ui + src/components/fx" /><LayerCard title="文档与机器事实" desc="docs/**/*.md + docs/data/*.json" /><LayerCard title="src/reports" desc="报告/简报渲染层" /></LayerRow><LayerRow label="底座"><LayerCard title="theme/fx-theme.css" desc="公司 token 和 shadcn 语义槽" /><LayerCard title="package.json" desc="依赖、脚本和构建命令" /><LayerCard title="Vite + React + Tailwind" desc="本网站的运行与构建技术栈" /></LayerRow></div></TabsContent><TabsContent value="relations" className="mt-0"><FileRelationMap relations={systemRelations.site} /></TabsContent></Tabs>;
}
